import "oaidl.idl";
import "ocidl.idl";

[
	uuid("36021344-93CA-4F02-B0AB-3A48AD734813"),	// GUID biblioteki typów 
	helpstring("Klasa testowa"),
	lcid(0x0415),	// locale 409-en_us, 415-pl
	version(1.0)	// wersja	
]

library KlasaLib
{
	importlib("stdole.tlb");
	import "oaidl.idl";
	[object, uuid("442A7716-E106-4279-9BC0-9C1B4ED1779B")]	// GUID interfejsu
	interface IKlasa2 : IUnknown {
		HRESULT Test([in]BSTR i);
	};

	[uuid("3F7A6746-5F7C-4A1C-BA61-E2C5C79CC096")]	// GUID klasy
	coclass Klasa2
	{
		interface IKlasa2;
	};
}
